### ISSUE TITLE
yicon init失败

### ISSUE THREAD

**Issue by frameZhang** [YMFE/yicon#32]
资源获取失败。只有一个空的src

**Comment by JasonFang93** [comment]
在 init 时，会去 github 上拉取源码，你看下是不是因为请求太慢，代码没拉下来导致的。
如果还不行，麻烦提供下你的部署的环境（包括系统、node、npm 版本）等

**Comment by frameZhang** [comment]
请问一下，我用windows 来init 老是提示我”文件夹不为空”，但是我就是空的啊。还有一个问题，就是windows下面得自己dir改成ls

**Comment by frameZhang** [comment]
![qq 20180306232206](https://user-images.githubusercontent.com/18166937/37040618-3fa23052-2195-11e8-906d-bc3cdd1f776d.png)
![qq 20180306232212](https://user-images.githubusercontent.com/18166937/37040619-3fdeac30-2195-11e8-9a2f-28159715597d.png)

**Comment by frameZhang** [comment]
老兄 windows 下面 有问题？

**Comment by frameZhang** [comment]
![1](https://user-images.githubusercontent.com/18166937/37045220-672d547a-21a0-11e8-9414-b2b03dc67a10.png)
老兄 为什么安装好了 我直接跑webpack 提示没有诶- -

**Comment by JasonFang93** [comment]
在 Windows 上可以跑，只不过初始化工具支持不是很好，在文档上有标示，部署系统要求 Linux/Unix，你是要在 windows 服务器上部署吗，你可以试试[docker镜像](https://github.com/YMFE/YIcon-Docker) 或者用 [git  bash](https://gitforwindows.org/)，别用 Windows 自带的 cmd

**Comment by frameZhang** [comment]
您好，我使用osx来跑好像还是有问题这是为什么呢？是我的工具有问题吗？webpack-cli？

**Comment by frameZhang** [comment]
我的webpack 是4.1.0版本，然后webpack-cli 是2.0.10

**Comment by frameZhang** [comment]
系统：osx 10.13.3
node：v9.4.0
npm：5.6.0

**Comment by frameZhang** [comment]
带宽100m

**Comment by frameZhang** [comment]
yicon init还是失败

**Comment by frameZhang** [comment]
还有，git下来的代码和github上的不一样。。
