### ISSUE TITLE
Yicon 运行webpack的时候出现问题

### ISSUE THREAD

**Issue by frameZhang** [YMFE/yicon#33]
您好，我不知道是哪里出现了问题：
![image](https://user-images.githubusercontent.com/18166937/37103673-ba7b4216-2265-11e8-98d2-8a251cc309e6.png)
我重新配置过很多次项目了，但是还是报错，不知道是哪里出了问题，麻烦解答一下，谢谢。

**Comment by JasonFang93** [comment]
没有用过 webpack-cli，不确定是不是 webpack-cli 的问题，你装 webpack 试试

**Comment by jgx-jay** [comment]
尝试下单独安装webpack
