### ISSUE TITLE
配置login登录的时候，tokenUrl返回的格式能不能给一个

### ISSUE THREAD

**Issue by frameZhang** [YMFE/yicon#34]
config.json下的login的tokenUrl，所需要的返回数据的格式是什么？能不能给我参考一哈？因为我这边配置之后报错。
![image](https://user-images.githubusercontent.com/18166937/37191562-6cc7dade-239b-11e8-9b41-ce2966f130b1.png)

**Comment by JasonFang93** [comment]
```json
{
      "ssoType": "cas",
      "authUrl": "https://cas.test.com/caso/login.html?service={{service}}",
      "tokenUrl": "https://cas.test.com/caso/valid?service={{service}}&ticket={{token}}",
      "serviceUrl": "http://test.xxx.com:8080",
      "adminList": []
}
```

**Comment by frameZhang** [comment]
您好，请问这个adminList你们文档上是用的单引号，要报错把？而且为什么我设置了管理员登录上去还是普通用户额？

**Comment by frameZhang** [comment]
![image](https://user-images.githubusercontent.com/18166937/37263819-ddb6cf66-25e4-11e8-99a6-cb31d867edb8.png)

![image](https://user-images.githubusercontent.com/18166937/37195703-e8707642-23ae-11e8-8162-c2ad4fd9caf8.png)
没有出现，权限控制的选项

**Comment by frameZhang** [comment]
建议 文档该更新一次了

**Comment by JasonFang93** [comment]
每次登陆时会校验 adminList 中的值，你 adminList 中的值跟写入数据库 user 表的 name 字段是一样的吗？你试下，重新退出下再登录试试
关于文档，后面会抽时间在整理下

**Comment by frameZhang** [comment]
您好，我这边确认了是一样的，但是还是没有权限的选项。
![image](https://user-images.githubusercontent.com/18166937/37263143-ab68b22a-25e1-11e8-9aba-da5581b046a7.png)
![image](https://user-images.githubusercontent.com/18166937/37263156-b97b9da0-25e1-11e8-8c07-09ac946b378f.png)
![image](https://user-images.githubusercontent.com/18166937/37263710-58daff56-25e4-11e8-90fa-bcdbcab57b17.png)

**Comment by frameZhang** [comment]
您好，还有一个问题请教，请问您们这边yicon init是从哪里拉的代码？需要翻墙吗？我在家拉取只成功过一次，在公司拉不下来代码。

**Comment by frameZhang** [comment]
不好意思，现在才看见，不好意思。我试了很多次，换成数字和字符都不行。我已经确定是一样的了。






在 2018-03-09 16:51:29，"Jason" <notifications@github.com> 写道：


每次登陆时会校验 adminList 中的值，你 adminList 中的值跟写入数据库 user 表的 name 字段是一样的吗？你试下，重新退出下再登录试试
关于文档，后面会抽时间在整理下

**Comment by leihao2016** [comment]
同样的问题，登陆成功返回的json格式是什么样的，有童鞋搞定了这个登陆了吗，指点一下，谢谢！

**Comment by leihao2016** [comment]
@frameZhang 你的登陆打通了吗，能不能指点下呢，谢谢
