### ISSUE TITLE
请问如何绕过单点登录？或者有没有推荐的online sso

### ISSUE THREAD

**Issue by 18672786357** [YMFE/yicon#36]
请问如何绕过单点登录？或者有没有推荐的online sso

**Comment by JasonFang93** [comment]
没有试过 online sso，不好推荐，你可以试试 [Yicon Docker](https://github.com/YMFE/YIcon-Docker) ，提供了个简单的用户登录系统

**Comment by 18672786357** [comment]
thanks,可以让我加入用户反馈群吗？
